name: CI

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  test:
    if: "!contains(toJson(github.event.commits), '[skip ci]')"
    strategy:
      matrix:
        node-version: [12.13.x]
        ts-version: [3.9.x]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} & Typescript ${{ matrix.ts-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        yarn install
        npx lerna bootstrap
        npx lerna run link
        yarn add typescript@${{ matrix.ts-version }} --dev
    - run: yarn test
    - name: Coverage
      uses: codecov/codecov-action@v1
      if: matrix.node-version == '12.13.x' && matrix.ts-version == '3.9.x' && github.ref == 'refs/heads/master'
